"""
Detection signals for Provenance Guard.

Signal 1 (llm_signal):        semantic / holistic — Groq LLM judgment
Signal 2 (stylometric_signal): structural / statistical — pure Python

Both signals return an "ai_likelihood" score in [0.0, 1.0], where 0.0 means
confidently human-written and 1.0 means confidently AI-generated. 0.5 means
the signal found nothing decisive either way.
"""
import os
import re
import json
import statistics

GROQ_MODEL = "llama-3.3-70b-versatile"


def _get_groq_client():
    """Lazily build a Groq client. Returns None if no API key is configured,
    so the pipeline still runs (in fallback mode) without crashing."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None
    from groq import Groq
    return Groq(api_key=api_key)


def llm_signal(text: str) -> dict:
    """
    Signal 1: ask an LLM to holistically judge whether text reads as
    human-written or AI-generated.

    What it captures: semantic and stylistic coherence as a whole — voice,
    idiosyncrasy, typical AI "tells" (hedging, generic transitions, uniform
    rhythm) — the kind of judgment a careful human reader would make.

    What it misses: it can be fooled by AI text that has been lightly
    edited by a human, or by human writing that happens to be very formal
    and even in tone (see planning.md "anticipated edge cases").

    Returns: {"score": float, "reasoning": str, "source": "groq"|"fallback"}
    """
    client = _get_groq_client()
    if client is None:
        return _llm_fallback("no GROQ_API_KEY configured")

    prompt = (
        "You are an AI content detector. Read the passage below and judge "
        "whether it was most likely written by a human or generated by an AI "
        "language model. Consider stylistic coherence, naturalness of voice, "
        "idiosyncrasy, and typical AI tells (hedging phrases, generic "
        "transitions, uniform sentence rhythm).\n\n"
        "Respond with ONLY a JSON object, no other text, in this exact format:\n"
        '{"ai_likelihood": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}\n\n'
        "ai_likelihood should be 0.0 if you are confident the text is "
        "human-written, 1.0 if you are confident it is AI-generated, and "
        "near 0.5 if you are genuinely unsure.\n\n"
        f"Passage:\n\"\"\"\n{text}\n\"\"\""
    )

    try:
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=200,
        )
        raw = resp.choices[0].message.content.strip()
        raw = re.sub(r"^```(json)?|```$", "", raw, flags=re.MULTILINE).strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_likelihood", 0.5))
        score = max(0.0, min(1.0, score))
        return {
            "score": score,
            "reasoning": parsed.get("reasoning", ""),
            "source": "groq",
        }
    except Exception as e:
        fallback = _llm_fallback(f"groq call failed ({e})")
        return fallback


def _llm_fallback(reason: str) -> dict:
    """
    Used only when Groq is unavailable (no key, network error, bad response).
    NOT a real signal — it exists so the pipeline degrades to "uncertain"
    rather than crashing or silently guessing. Documented in README.
    """
    return {"score": 0.5, "reasoning": reason, "source": "fallback"}


_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+")
_WORD_RE = re.compile(r"[A-Za-z']+")


def stylometric_signal(text: str) -> dict:
    """
    Signal 2: pure-Python statistical heuristics on sentence structure and
    vocabulary. Independent of Signal 1 — it never reads the text
    "holistically," only measures it.

    Metrics:
      - sentence length coefficient of variation (CV): AI text tends to
        produce more uniform sentence lengths than human writing.
        Low CV -> higher ai_likelihood.
      - type-token ratio (TTR): unique words / total words. AI text tends
        to reuse a narrower vocabulary relative to length.
        Low TTR -> higher ai_likelihood.

    Blind spot: both metrics are sensitive to text length — very short
    passages don't have enough sentences/words for CV or TTR to mean much,
    and TTR naturally drops as any text (human or AI) gets longer. Short
    or very long inputs are flagged as "uncertain" rather than scored.

    Returns: {"score": float, "metrics": {...}, "source": "stylometric"}
    """
    sentences = [s.strip() for s in _SENT_SPLIT.split(text.strip()) if s.strip()]
    words = _WORD_RE.findall(text.lower())

    if len(sentences) < 2 or len(words) < 5:
        return {
            "score": 0.5,
            "metrics": {"sentence_count": len(sentences), "word_count": len(words),
                        "note": "too short to score reliably"},
            "source": "stylometric",
        }

    sentence_lengths = [len(_WORD_RE.findall(s)) for s in sentences]
    sentence_lengths = [n for n in sentence_lengths if n > 0]
    mean_len = statistics.mean(sentence_lengths)
    stdev_len = statistics.pstdev(sentence_lengths)
    cv = (stdev_len / mean_len) if mean_len > 0 else 0.0

    ttr = len(set(words)) / len(words)

    # Low CV (uniform sentence length) -> AI-like. CV ~0 -> 1.0; CV >= 0.8 -> 0.0
    cv_ai_score = max(0.0, min(1.0, 1.0 - (cv / 0.8)))

    # Low TTR (repetitive vocabulary) -> AI-like. TTR <= 0.4 -> 1.0; TTR >= 0.8 -> 0.0
    ttr_ai_score = max(0.0, min(1.0, (0.8 - ttr) / 0.4))

    combined = 0.5 * cv_ai_score + 0.5 * ttr_ai_score

    return {
        "score": round(combined, 4),
        "metrics": {
            "sentence_count": len(sentences),
            "word_count": len(words),
            "mean_sentence_length": round(mean_len, 2),
            "sentence_length_cv": round(cv, 4),
            "type_token_ratio": round(ttr, 4),
        },
        "source": "stylometric",
    }


# The LLM signal is weighted much higher because it captures holistic
# semantic and stylistic coherence that heuristics structurally cannot see,
# and it is far more reliable on short passages (stylometric CV/TTR are
# noisy below a few dozen words — see stylometric_signal's docstring). The
# stylometric signal is kept at a real but modest weight so it still acts
# as an independent check: it can pull a confident-but-wrong LLM verdict
# toward "uncertain" without being able to override it outright.
LLM_WEIGHT = 0.85
STYLE_WEIGHT = 0.15


def combine_signals(llm_result: dict, style_result: dict) -> float:
    combined = LLM_WEIGHT * llm_result["score"] + STYLE_WEIGHT * style_result["score"]
    return round(max(0.0, min(1.0, combined)), 4)
